"""add_tenant_model_and_tenant_id_fks

Revision ID: 054afe0f5822
Revises: 8afd56c3f9ff
Create Date: 2026-07-30 13:29:06.736207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054afe0f5822'
down_revision: Union[str, None] = '8afd56c3f9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_batches_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('cargo_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cargo_registrations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_cargo_registrations_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_certificates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_certificates_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_collections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_collections_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('item_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_item_inventory_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_item_inventory_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('item_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_item_rates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_item_rates_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_products_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shipments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_shipments_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_taxonomies_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_taxonomies_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('taxonomy_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_taxonomy_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_taxonomy_items_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('taxonomy_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_taxonomy_nodes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_taxonomy_nodes_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_users_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_warehouses_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_warehouses_tenant_id', 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_warehouses_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_warehouses_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('taxonomy_nodes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_taxonomy_nodes_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_taxonomy_nodes_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('taxonomy_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_taxonomy_items_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_taxonomy_items_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_taxonomies_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_taxonomies_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shipments_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shipments_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('item_rates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_rates_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_item_rates_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('item_inventory', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_inventory_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_item_inventory_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collections_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_collections_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_certificates_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_certificates_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('cargo_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cargo_registrations_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cargo_registrations_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batches_tenant_id', type_='foreignkey')

    # ### end Alembic commands ###
