"""initial_schema

Revision ID: 386555668c3a
Revises: 
Create Date: 2026-07-30 10:09:53.279832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386555668c3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('avg_humidity_percent', sa.Float(), nullable=True),
    sa.Column('last_stocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['taxonomy_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_inventory_id'), 'item_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_item_inventory_item_id'), 'item_inventory', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_inventory_warehouse_id'), 'item_inventory', ['warehouse_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('INBOUND', 'OUTBOUND', 'TRANSFER', 'ADJUSTMENT', 'WRITE_OFF', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.Enum('SHIPMENT', 'RECEIPT', 'TRANSFER_ORDER', 'AUDIT', 'MANUAL', name='movementreference'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('moved_by', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['taxonomy_items.id'], ),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_item_id'), 'inventory_movements', ['item_id'], unique=False)
    op.add_column('batches', sa.Column('item_id', sa.Integer(), nullable=True))
    op.add_column('batches', sa.Column('serial_number', sa.String(length=255), nullable=True))
    op.add_column('batches', sa.Column('manufacturer_part_number', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_batches_item_id'), 'batches', ['item_id'], unique=False)
    op.create_index(op.f('ix_batches_serial_number'), 'batches', ['serial_number'], unique=False)
    op.create_foreign_key(None, 'batches', 'taxonomy_items', ['item_id'], ['id'])
    op.add_column('certificates', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_certificates_item_id'), 'certificates', ['item_id'], unique=False)
    op.create_foreign_key(None, 'certificates', 'taxonomy_items', ['item_id'], ['id'])
    op.add_column('products', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_item_id'), 'products', ['item_id'], unique=False)
    op.create_foreign_key(None, 'products', 'taxonomy_items', ['item_id'], ['id'])
    op.add_column('shipment_batches', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shipment_batches_item_id'), 'shipment_batches', ['item_id'], unique=False)
    op.create_foreign_key(None, 'shipment_batches', 'taxonomy_items', ['item_id'], ['id'])
    op.add_column('shipment_tracking_events', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shipment_tracking_events_item_id'), 'shipment_tracking_events', ['item_id'], unique=False)
    op.create_foreign_key(None, 'shipment_tracking_events', 'taxonomy_items', ['item_id'], ['id'])
    op.add_column('traceability_events', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_traceability_events_item_id'), 'traceability_events', ['item_id'], unique=False)
    op.create_foreign_key(None, 'traceability_events', 'taxonomy_items', ['item_id'], ['id'])
    op.add_column('warehouse_items', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_warehouse_items_item_id'), 'warehouse_items', ['item_id'], unique=False)
    op.create_foreign_key(None, 'warehouse_items', 'taxonomy_items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_items', type_='foreignkey')
    op.drop_index(op.f('ix_warehouse_items_item_id'), table_name='warehouse_items')
    op.drop_column('warehouse_items', 'item_id')
    op.drop_constraint(None, 'traceability_events', type_='foreignkey')
    op.drop_index(op.f('ix_traceability_events_item_id'), table_name='traceability_events')
    op.drop_column('traceability_events', 'item_id')
    op.drop_constraint(None, 'shipment_tracking_events', type_='foreignkey')
    op.drop_index(op.f('ix_shipment_tracking_events_item_id'), table_name='shipment_tracking_events')
    op.drop_column('shipment_tracking_events', 'item_id')
    op.drop_constraint(None, 'shipment_batches', type_='foreignkey')
    op.drop_index(op.f('ix_shipment_batches_item_id'), table_name='shipment_batches')
    op.drop_column('shipment_batches', 'item_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_item_id'), table_name='products')
    op.drop_column('products', 'item_id')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_index(op.f('ix_certificates_item_id'), table_name='certificates')
    op.drop_column('certificates', 'item_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batches_serial_number'), table_name='batches')
    op.drop_index(op.f('ix_batches_item_id'), table_name='batches')
    op.drop_column('batches', 'manufacturer_part_number')
    op.drop_column('batches', 'serial_number')
    op.drop_column('batches', 'item_id')
    op.drop_index(op.f('ix_inventory_movements_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_item_inventory_warehouse_id'), table_name='item_inventory')
    op.drop_index(op.f('ix_item_inventory_item_id'), table_name='item_inventory')
    op.drop_index(op.f('ix_item_inventory_id'), table_name='item_inventory')
    op.drop_table('item_inventory')
    # ### end Alembic commands ###
