"""add_item_shipment_status

Revision ID: 5f942318555b
Revises: b9cbf99bbd77
Create Date: 2026-07-30 12:14:49.405048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f942318555b'
down_revision: Union[str, None] = 'b9cbf99bbd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_batches', sa.Column('item_shipment_status', sa.Enum('PENDING', 'LOADED', 'IN_TRANSIT', 'DELIVERED', 'EXCEPTION', name='itemshipmentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment_batches', 'item_shipment_status')
    # ### end Alembic commands ###
