"""add_certificate_request

Revision ID: 819dbcaa07cc
Revises: 828a82cbf5e4
Create Date: 2026-07-30 11:19:33.481338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819dbcaa07cc'
down_revision: Union[str, None] = '828a82cbf5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('requested_type', sa.Enum('ORIGIN', 'ORGANIC', 'HALAL', 'QUALITY', 'SAFETY', 'FAIR_TRADE', 'GLOBALGAP', 'GRASP', 'SMETA', 'BRC', 'IFS', 'FSSC22000', 'ISO22000', 'RAINFOREST_ALLIANCE', 'UTZ', 'MSC', 'ASC', 'CUSTOM', name='certificatetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='certificaterequeststatus'), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applicant_notes', sa.Text(), nullable=True),
    sa.Column('target_market', sa.String(length=100), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo_registrations.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['taxonomy_items.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_requests_cargo_id'), 'certificate_requests', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_certificate_requests_id'), 'certificate_requests', ['id'], unique=False)
    op.create_index(op.f('ix_certificate_requests_item_id'), 'certificate_requests', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_requests_item_id'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_id'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_cargo_id'), table_name='certificate_requests')
    op.drop_table('certificate_requests')
    # ### end Alembic commands ###
