"""add_cargo_registration

Revision ID: 828a82cbf5e4
Revises: 577747fbe587
Create Date: 2026-07-30 11:11:54.540653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828a82cbf5e4'
down_revision: Union[str, None] = '577747fbe587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('origin_location', sa.String(length=255), nullable=True),
    sa.Column('destination_location', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTERED', 'CERTIFIED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='cargostatus'), nullable=True),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('carrier_ref', sa.String(length=255), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('estimated_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['taxonomy_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_registrations_id'), 'cargo_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_cargo_registrations_item_id'), 'cargo_registrations', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_registrations_item_id'), table_name='cargo_registrations')
    op.drop_index(op.f('ix_cargo_registrations_id'), table_name='cargo_registrations')
    op.drop_table('cargo_registrations')
    # ### end Alembic commands ###
