"""add_item_rate

Revision ID: 8afd56c3f9ff
Revises: 5f942318555b
Create Date: 2026-07-30 12:21:55.091431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afd56c3f9ff'
down_revision: Union[str, None] = '5f942318555b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('origin_region', sa.String(length=255), nullable=False),
    sa.Column('destination_region', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('transit_days_min', sa.Integer(), nullable=True),
    sa.Column('transit_days_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['taxonomy_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_rates_id'), 'item_rates', ['id'], unique=False)
    op.create_index(op.f('ix_item_rates_item_id'), 'item_rates', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_rates_item_id'), table_name='item_rates')
    op.drop_index(op.f('ix_item_rates_id'), table_name='item_rates')
    op.drop_table('item_rates')
    # ### end Alembic commands ###
